Increase the monitor throughput: increase the default fetch size, make it configurable.
elastic/fleet-server pull request #171
Opened 2021-03-25 18:28 UTC by aleksmaus

## What does this PR do?

Increases the monitor throughput:

* Increase the monitor fetch size to 1000 by default, the max number of documents fetched at once.
* Makes the monitor fetch size configurable.
* Decreased the pause between fetches from 50ms to 10ms.

## Why is it important?

Tuning of the throughput.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas

2021-03-25 18:33 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Ffleet-server%2FPR-171/detail/PR-171/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Ffleet-server%2FPR-171/detail/PR-171/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Ffleet-server%2FPR-171/detail/PR-171/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Ffleet-server%2FPR-171/detail/PR-171/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://fleet-server_171.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #171 opened`



* Start Time: 2021-03-25T18:29:12.313+0000


* Duration: 5 min 33 sec


* Commit: bbfe72799206cbd4a08d49a0b2242a3923571c05



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 64  |
| Skipped      | 0 |
| Total        | 64   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/fleet-server/job/PR-171/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Ingest-manager/job/fleet-server/job/PR-171/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-03-26 13:00 UTC, blakerouse requested changes
The location of the configuration options needs to be adjusted.

2021-03-26 13:00 UTC, blakerouse commented on internal/pkg/config/config.go
> +	Monitor Monitor `config:"monitor"`
This also needs to be added under the input and not at this top-level.

2021-03-26 14:29 UTC, aleksmaus commented
Updated, moved the monitor config into input config.

2021-03-29 11:45 UTC, blakerouse approved these changes
Thanks for the fixes.

2021-03-29 12:57 UTC, merged