Remove direct pkg/errors dependency
elastic/fleet-server pull request #2153
Opened 2022-12-02 19:25 UTC by michel-laterman

Go has error wrapping as part. of the stdlib since v1.13.0.
This PR removes an external library that was used in the repo to provide the same functions.
The library is still an indirect requirement as other imports use it.

2022-12-02 19:33 UTC, cmacknz requested changes
Some of these replacements don't have equivalent behaviour, I tried this in Beats and gave up because I had to manually audit every usage of `errors.Wrap()` where the error could be `nil`. This looks more manageable, you just need to add some additional special handling for cases where `errors.Wrap` is in the last `return` of a function and the error it is passed could be `nil`.


https://github.com/elastic/beats/issues/31702

2022-12-02 19:37 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/fleet-server%2Ffleet-server-mbp%2FPR-2153/detail/PR-2153/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/fleet-server%2Ffleet-server-mbp%2FPR-2153/detail/PR-2153/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://fleet-ci.elastic.co/blue/organizations/jenkins/fleet-server%2Ffleet-server-mbp%2FPR-2153/detail/PR-2153/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://fleet-ci.elastic.co/blue/organizations/jenkins/fleet-server%2Ffleet-server-mbp%2FPR-2153/detail/PR-2153/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://fleet-server_2153.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/fleet-ci/transactions/view?rangeFrom=2022-12-02T19:15:52.925Z&rangeTo=2022-12-02T19:35:52.925Z&transactionName=BUILD+fleet-server%2Ffleet-server-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=fe5a08ef21fa5daca40272c89b678a5f&transactionId=0ac3d6dc3e27e4b0)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-12-02T19:25:52.925+0000


* Duration: 12 min 31 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 393  |
| Skipped      | 1 |
| Total        | 394   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :green_heart: Flaky test report
Tests succeeded.



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-12-02 22:36 UTC, michel-laterman commented on internal/pkg/api/handleArtifacts.go
> -	return artifact, errors.Wrap(err, "fetchArtifact")
I'll make the changes

2022-12-05 12:53 UTC, AndersonQ approved these changes

2022-12-05 12:53 UTC, AndersonQ commented on internal/pkg/api/handleEnroll.go
> +			err := errors.New("apikey index failed to refresh")
:+1:

2022-12-05 15:38 UTC, cmacknz approved these changes

2022-12-05 19:31 UTC, merged